### ISSUE TITLE
Remove if else condition and use es6 Arrow function without using return keyword

### ISSUE THREAD

**Issue by nishant-jain-94** [sro-boeing-wave-2/deaf-grandma-js-problem-angita1#3]
https://github.com/sro-boeing-wave-2/deaf-grandma-js-problem-angita1/blob/866ccaaa211a86dd5c6b416dae049778f771d21f/isUpperCase.js#L10-L15

**Comment by yaiphabee** [comment]
Remove if-else and return keyword from the arrow function
